### ISSUE TITLE
Error with game Version 0.9.24.11182

### ISSUE THREAD

**Issue by w-gates** [Pasukaru/DSP-Mods#13] opened 2022-01-20 15:57 UTC
When placing a PLS, I got the attached error which looks to be caused by the AutoStationConfig mod.

![image](https://user-images.githubusercontent.com/5648196/150374566-ce22d0f9-35bc-455b-a76e-c487363b0795.png)

**Comment by Tank420UK** [comment] 2022-01-21 12:30
> When placing a PLS, I got the attached error which looks to be caused by the AutoStationConfig mod.
> 
> ![image](https://user-images.githubusercontent.com/5648196/150374566-ce22d0f9-35bc-455b-a76e-c487363b0795.png)

Confirmed with trial and error to be this mod causing the issue. 

For additional info, it seems to stop all logistic drones and vessels dead in their tracks where ever they are and the tower seems to persist once removed and continues to draw power.

**Comment by Pasukaru** [comment] 2022-01-21 12:42
The mod is almost 1 year old. Whatever updates happened, they broke this mod.

I'm not actively playing DSP currently, so I won't fix it any time soon. But feel free to submit a PR, that would be much appreciated!

**Comment by w-gates** [comment] 2022-01-21 13:05
> The mod is almost 1 year old. I don't know what updates where made to the game in this time, but they broke this mod.
> 
> Looks like at least one method got removed to remove items from an inventory. I don't know if there are other changes that will cause errors.
> 
> I'm not actively playing DSP currently, so I won't fix it any time soon. But feel free to submit a PR, that would be much appreciated!

If you are not planning to update this yourself, please mark the mod as depreciated on the [Mod Manager](https://dsp.thunderstore.io/package/Pasukaru/AutoStationConfig/) website so new players don't download it while it is not working.

**Comment by nclow** [comment] 2022-01-22 04:43
It looks like the method signature for StorageComponent.TakeItem changed to `public int TakeItem(int itemId, int count, out int inc)`. I can't really tell what that third argument does though just from the decompiled code (some kind of increment? A stack size?) and I know zilch about Unity modding or I'd try to fix it myself.

**Comment by w-gates** [comment] 2022-01-22 13:02
[AutoLogisticsDroneSetup](https://dsp.thunderstore.io/package/Gimbalhawk/AutoLogisticsDroneSetup/) is a partial replacement for AutoStationConfig.

**Comment by Chemie99** [comment] 2022-01-23 16:44
> [AutoLogisticsDroneSetup](https://dsp.thunderstore.io/package/Gimbalhawk/AutoLogisticsDroneSetup/) is a partial replacement for AutoStationConfig.

I added a request to that one hoping for similar functional adds.  Too bad this one is not supported, it was a huge time saver and I am now going to forget every time a place a ILS (Blueprints do help though)

**Comment by nclow** [comment] 2022-01-23 19:10
I have a [PR](https://github.com/Pasukaru/DSP-Mods/pull/14) that hopefully the author can review. If not you can get my [patched dll](https://drive.google.com/file/d/1qYV8u-xtS-bGN2d0UQ1YOJYJuM87vH_E/view?usp=sharing) or patch it yourself with dnspy.

**Comment by Chemie99** [comment] 2022-01-23 20:15
> I have a [PR](https://github.com/Pasukaru/DSP-Mods/pull/14) that hopefully the author can review. If not you can get my [patched dll](https://drive.google.com/file/d/1qYV8u-xtS-bGN2d0UQ1YOJYJuM87vH_E/view?usp=sharing) or patch it yourself with dnspy.

Do you plan on forking and uploading to Thunderstore?

**Comment by Chemie99** [comment] 2022-01-23 20:21
> I have a [PR](https://github.com/Pasukaru/DSP-Mods/pull/14) that hopefully the author can review. If not you can get my [patched dll](https://drive.google.com/file/d/1qYV8u-xtS-bGN2d0UQ1YOJYJuM87vH_E/view?usp=sharing) or patch it yourself with dnspy.

Crashes for me
![image](https://user-images.githubusercontent.com/94768495/150696585-0f1c9c02-78e8-4329-83e4-5d75d032db59.png)

**Comment by nclow** [comment] 2022-01-23 20:34
> > I have a [PR](https://github.com/Pasukaru/DSP-Mods/pull/14) that hopefully the author can review. If not you can get my [patched dll](https://drive.google.com/file/d/1qYV8u-xtS-bGN2d0UQ1YOJYJuM87vH_E/view?usp=sharing) or patch it yourself with dnspy.
> 
> Crashes for me ![image](https://user-images.githubusercontent.com/94768495/150696585-0f1c9c02-78e8-4329-83e4-5d75d032db59.png)

Did you build from the code in the PR? Or use the patched dll? This is the same as the previous error, so it seems likely you don't have the fix in place.

The old dll is 14,336 bytes.
The new dll is 14,848 bytes

**Comment by Pasukaru** [comment] 2022-01-24 15:24
Fixed as of #14

**Closed by Pasukaru** 2022-01-24 15:24 UTC

**Comment by Chemie99** [comment] 2022-01-24 15:55
> > > I have a [PR](https://github.com/Pasukaru/DSP-Mods/pull/14) that hopefully the author can review. If not you can get my [patched dll](https://drive.google.com/file/d/1qYV8u-xtS-bGN2d0UQ1YOJYJuM87vH_E/view?usp=sharing) or patch it yourself with dnspy.
> > 
> > 
> > Crashes for me ![image](https://user-images.githubusercontent.com/94768495/150696585-0f1c9c02-78e8-4329-83e4-5d75d032db59.png)
> 
> Did you build from the code in the PR? Or use the patched dll? This is the same as the previous error, so it seems likely you don't have the fix in place.
> 
> The old dll is 14,336 bytes. The new dll is 14,848 bytes

I used the new DLL you had linked to (14,848 size); Manually copied it to the MOD folder overwriting the old DLL

**Comment by Pasukaru** [comment] 2022-01-24 15:57
> I used the new DLL you had linked to (14,848 size); Manually copied it to the MOD folder overwriting the old DLL

Please use r2modman to download the latest version. 1.3.2 is available now.

**Comment by Chemie99** [comment] 2022-01-24 16:11
> > I used the new DLL you had linked to (14,848 size); Manually copied it to the MOD folder overwriting the old DLL
> 
> Please use r2modman to download the latest version. 1.3.2 is available now. https://dsp.thunderstore.io/package/Pasukaru/AutoStationConfig/

Yes, that version did work without crash.  Thanks
